### ISSUE TITLE
Global variables in outer scope

### ISSUE THREAD

**Issue by pavelkharitenko** [precice/julia-bindings#10]
Currently, the path to the libprecice.so binary is provided by a global variable [`libprecicePath`](https://github.com/precice/julia-bindings/blob/e16aa47d8e2546c97d4c1fc0067e6b54e83473a3/src/PreCICE.jl#L7) in the module. However, global variables are limiting the performance, [according to the documentation](https://docs.julialang.org/en/v1/manual/performance-tips/#Avoid-global-variables), and an interesting test case [here](https://gist.github.com/flcong/2eba0189d7d3686ea9633a6d14398931)

There are two (proper) possible solutions
- declaring [const libprecicePath = ...](https://docs.julialang.org/en/v1/manual/variables-and-scoping/#Constants) 
- not having any paths but create a preCICE_jll package that will provide the necessary binaries to the module, like [here](https://github.com/JuliaIO/LibSerialPort.jl/blob/4fc7f7ef67591f58aa596b11f32d9482bea1153b/src/wrap.jl#L11)

Any of those two solutions will require a way to configure the binary location, should users want to point to their custom installation. `MPI.jl` is a prime example, as it installs its own MPI JLL but users can override it to their system MPI implementation as seen [here](https://juliaparallel.github.io/MPI.jl/latest/configuration/#Using-a-system-provided-MPI).

**Comment by fsimonis** [comment]
No performance claims without measurements. :wink: 

Also, the linked resources describe the problem of using a global in hot code.
The real work happens either in the Solver or inside preCICE. The preCICE API is simply a gateway between the two.

My _guess_ is, that the API won't be called often enough to make any measurable difference.

Feel challenged to prove me wrong! :rocket:

**Comment by IshaanDesai** [comment]
This issue makes performance based claims without actually running large cases, hence closing this for now.
