### ISSUE TITLE
Warn user, if julia version is too old

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/julia-bindings#15]
I just tried using the julia bindings and (of course) did not read the documentation properly. I installed julia via `sudo apt install julia` and got version 1.4.1. This led to an error when trying to run the solverdummies. By upgrading julia to version 1.7.2 I managed to resolve this error.

Is it possible to warn the user or throw an error, if the julia version is too old? This would help users like me that do not read properly.

**Comment by erikscheurer** [comment]
It is possible to change the compatibility in [Project.toml](https://github.com/precice/julia-bindings/blob/46869316f076fcb1e05f203ea7a9a903d8bacc14/Project.toml#L7) to the last compatible version. Then the user gets a message when installing the bindings. 
However, unless you have julia version 0.x then its not a warning but just a message:
```julia-repl
(@v1.4) pkg> dev ./julia-bindings/
Path `./julia-bindings/` exists and looks like the correct package. Using existing path.
  Resolving package versions...
julia version requirement for package `PreCICE [57fbd4af]` not satisfied
   Updating `~/.julia/environments/v1.4/Project.toml`
```
The package manager also allows for [different compatibility systems](https://pkgdocs.julialang.org/v1/compatibility/#Caret-specifiers) where from my understanding the caret specifier would be the correct choice.

**Comment by IshaanDesai** [comment]
@erikscheurer the ideal thing that we want is that the installation of the bindings does not proceed if Julia version is `< 1.6`. The user should then receive an error about the incompatible Julia version. As we know that the bindings do not work with earlier Julia versions than 1.6, we can straight away drop support for them and just produce an Error.

Can you open a pull request with such an implementation using either of the strategies you mentioned above?
