### ISSUE TITLE
Test bindings against latest Julia versions and add the versions to supported versions list

### ISSUE THREAD

**Issue by IshaanDesai** [precice/julia-bindings#19]
The bindings need to be tested with the [latest releases of Julia](https://github.com/JuliaLang/julia/releases) and the versions then need to be added to the setup.

**Comment by IshaanDesai** [comment]
> What tests should be made to check compatibility? Only if its able to load the bindings or the solverdummy as well? Any other tests? 

Ideally yes, the tests should run get the package into a container with a specific Julia version, and then run the solverdummy. We should do this for all compatible versions of Julia. But for now the test you have mentioned below is also sufficient.

> ```
> julia> ]
> pkg> test PreCICE
> ```
> 
> This basically just executes `using PreCICE;PreCICE.getVersionInformation()` and checks if there is an error

As a start you can install the latest Julia version on your local machine and try out the bindings. If they work then you can also change the Julia version to a few releases before the latest one and try again. Lets first manually make sure which versions the bindings work with before we start writing tests.

**Comment by erikscheurer** [comment]
In the [`testing` branch](https://github.com/precice/julia-bindings/tree/testing)  there is now a test for the solverdummies. So far, both tests succeed on the versions 1.6.5, 1.7.2, 1.8.0-beta1 of Julia which are available on the [download site](https://julialang.org/downloads/).

**Comment by IshaanDesai** [comment]
@erikscheurer can you open a pull request to `main` from the testing branch? I will review the tests and try things out myself then

**Comment by erikscheurer** [comment]
Can This PR be closed now?
