### ISSUE TITLE
Add tests to the bindings

### ISSUE THREAD

**Issue by IshaanDesai** [precice/julia-bindings#2]
The bindings need to be tested for possible bugs and other errors. Such a testing framework can take various forms and is often evolving naturally. For example, the [python-bindings mock test framework](https://github.com/precice/python-bindings/tree/develop/test) mocks the preCICE API and checks if the API functions in the bindings indeed pass the correct information to the preCICE API or not. Such a testing framework can be implemented for the julia bindings.

**Comment by uekerman** [comment]
A simple CI workflow that builds the bindings on every PR would already be an important first step.

**Comment by IshaanDesai** [comment]
Closed in https://github.com/precice/julia-bindings/pull/8
