### ISSUE TITLE
Remove the mpi-parallelization branch from this repository

### ISSUE THREAD

**Issue by pavelkharitenko** [precice/julia-bindings#3]
The `mpi-parallelization`-branch shows only a way of how this library can be used but adds no further functionality. 
Its content should be rather moved to the place made for documentation (or a repository like the [one from ajaust](https://github.com/ajaust/precice-parallel-solverdummies) than be merged into the core package.

**Comment by IshaanDesai** [comment]
@pavelkharitenko feel free to modify this issue to also document all the approaches in which MPI parallelization and native Julia parallelization can be used when a Julia code is coupled with preCICE. The various approaches we discussed earlier can be included in the documentation.

Whether or not we include the parallel solver dummies in the main branch is another story and we will decide that later. For now keeping the parallel solver dummies in a separate branch is no problem.

**Comment by pavelkharitenko** [comment]
Ok, I will then close this issue since we will keep this branch.
