### ISSUE TITLE
Instructions in README to add the package do not work

### ISSUE THREAD

**Issue by IshaanDesai** [precice/julia-bindings#4]
I tried to add the Julia bindings package following the instructions in the README and could not successfully use the package. The instructions work up to the point:
```
julia> ]
(@v1.4) pkg>
(@v1.4) pkg> add https://github.com/precice/julia-bindings.git
   Updating git-repo `https://github.com/precice/julia-bindings.git`
   Updating registry at `~/.julia/registries/General`
   Updating git-repo `https://github.com/JuliaRegistries/General.git`
  Resolving package versions...
   Updating `~/.julia/environments/v1.4/Project.toml`
  [57fbd4af] ~ PreCICE v0.1.0 #main (https://github.com/precice/julia-bindings.git)
   Updating `~/.julia/environments/v1.4/Manifest.toml`
  [57fbd4af] ~ PreCICE v0.1.0 #main (https://github.com/precice/julia-bindings.git)
```
but afterwards it is unclear how to go back to `julia>` and use the added package. I clicked `Ctrl + C` and got the following:
```
julia> using preCICE
ERROR: ArgumentError: Package preCICE not found in current path:
- Run `import Pkg; Pkg.add("preCICE")` to install the preCICE package.

Stacktrace:
 [1] require(::Module, ::Symbol) at ./loading.jl:892
```
Am I missing something here? I think the steps can be more elaborate here.

**Comment by pavelkharitenko** [comment]
Thanks for the notice. After using the package mode pkg>, you can go back to the julia> REPL by typing backspace. 
I will update the README and tag you to review and close this issue.

**Comment by pavelkharitenko** [comment]
@IshaanDesai I uploaded my changes to the [installatins-update](https://github.com/precice/julia-bindings/tree/update-installations) branch, feel free to change or extend it as well.

**Comment by IshaanDesai** [comment]
I can now successfully run `julia> using PreCICE` but when I try to run `getVersionInformation()` I see something like:
```
julia> getVersionInformation()
ERROR: TypeError: in ccall: first argument not a pointer or valid constant expression, expected Ptr, got Tuple{Symbol,String}
Stacktrace:
 [1] getVersionInformation() at /home/desaiin/.julia/packages/PreCICE/RjJaH/src/PreCICE.jl:275
 [2] top-level scope at REPL[3]:1
```
what could the problem be?

**Comment by pavelkharitenko** [comment]
1. What branch are you using?
2. Which version of Julis do you have?
3. How did you install Julia? apt-get or from their website?

The error is probably in one of these points.

**Comment by IshaanDesai** [comment]
>     1. What branch are you using?
> 
Main branch

>     2. Which version of Julia do you have?
> 

Julia version 1.4.1
>     3. How did you install Julia? apt-get or from their website?
> 

Installed using `apt-get`

**Comment by pavelkharitenko** [comment]
Thanks. I think I had those issues on 1.4.1 too. It should run on the latest stable release 1.6, which is not on the apt repository I think yet. 
So people that have this issue will either have to install from the Julia's website (what is generally recommended), or wait for a fix from us. I will look into making a fix to this, by making the code backwards compatible or extend the installation instructions.

**Comment by pavelkharitenko** [comment]
In the meantime, the fix would be to install Julia from their website. What mean by 'install from the website' is step 2. of [this](https://github.com/pavelkharitenko/julia-binding-for-preCICE) README.md Installation instructions.

**Comment by IshaanDesai** [comment]
Okay got it, so right now the bindings are only compatible with the latest stable release of Julia. 

> So people that have this issue will either have to install from the Julia's website (what is generally recommended), or wait for a fix from us. I will look into making a fix to this, by making the code backwards compatible or extend the installation instructions.

Lets clearly mention this in the README by adding a section **Dependencies** in which we explain how to install Julia and which versions of Julia are these bindings compatible with. For now it is sufficient that the bindings work with the latest stable release, lets wait to hear from potential if backward compatibility is required.

**Comment by pavelkharitenko** [comment]
The latest commits on `update-installations` now provide a **Dependencies** section, that lists the desired installation of Julia and the versions (that ran through with the workflow `TestJuliaVersions.yml` on the `test and ci` branch.)
